controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    revolute_joint_controller:
      type: position_controllers/JointPositionController
      joints:
        - camera_tilt_joint
        - head_yaw_joint
