controller_manager:
  ros__parameters:
    update_rate: 1000 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController

effort_controller:
  ros__parameters:
    joints:
      - head_yaw_joint
      - camera_tilt_joint
    interface_name: effort  
    command_interfaces:
      - effort  
    state_interfaces:
      - position
      - velocity
      - effort
